### ISSUE TITLE
US 02.02.01 - As an attendee, I want to upload a profile picture for a more personalized experience.

### ISSUE THREAD

**Issue by bnpower** [CMPUT301W24T56/fiftysix#15]
US 02.02.01
US 01.01.02
role: attendee
goal: upload a profile picture for a more personalized experience

## Estimation of effort
14 Story points

## Risk Level
Low

## Acceptance criteria
TBD

**Comment by Arsh0388** [comment]
I have to save them in the database.  so far i can open the camera, take the picture  and set the profile image.
