### ISSUE TITLE
US 01.03.01 - As an organizer, I want to send notifications to all attendees through the app.

### ISSUE THREAD

**Issue by bnpower** [CMPUT301W24T56/fiftysix#7]
US 01.03.01
role: organizer
goal: send notifications to all attendees through the app

## Estimation of effort
28 story points

## Risk Level
Medium

## Acceptance criteria
TBD

**Comment by Arsh0388** [comment]
done storing attendee ids and notifications in the database. on. the attendee side we will set a listener and get the notifications . otherwise attendee will only get the notifications once.
